feat: Forms embed component for XWalk
adobe-rnd/aem-boilerplate-xwalk pull request #11
Opened 2024-03-07 09:51 UTC by akasjain-lf

This PR provides ability to UE site author to embed Form inside a site page. Form can be a doc-based form (Sharepoint Excel or Google Drive) or AEM authored AF2 form.

PR for adding AEM Component - https://git.corp.adobe.com/CQ/sites-franklin/pull/51

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-03-07 09:56 UTC, nit23uec commented on component-definition.json
> +                  "rootPath": "/content/forms/af/..."
rootPath should be empty in template

2024-03-07 09:58 UTC, nit23uec commented on component-models.json
> +        "label": "Root Path"
label should be `Form Path`

2024-03-07 09:58 UTC, nit23uec commented on component-models.json
> +        "name": "rootPath",
I think we should persist it as `formPath` instead of rootPath

2024-03-07 09:59 UTC, nit23uec commented on component-definition.json
> +                  "rootPath": "/content/forms/af/..."
I'd prefer `formPath` in place of `rootPath`

2024-03-07 10:24 UTC, akasjain-lf commented on component-definition.json
> +                  "rootPath": "/content/forms/af/..."
Changed to formPath

2024-03-14 10:47 UTC, Buuhuu requested changes

2024-03-14 10:47 UTC, Buuhuu commented on component-models.json
> +        "component": "text-input",
should be `text`

2024-03-14 10:47 UTC, Buuhuu commented on component-definition.json
> +                "resourceType": "core/franklin/components/embedform/v1/embedform",
you can use the normal generic block. a custom AEM embedform component should no be needed.

If the form path is a link (starting with https?:// it will be rendered as <a> anyway). If it is a path and resolves to a resource it would also be rendered link.

2024-03-15 13:25 UTC, akasjain-lf commented on component-definition.json
> +                "resourceType": "core/franklin/components/embedform/v1/embedform",
I've used the generic block component with one text field to input form URL (sheet based) / path (AF2).

2024-03-22 12:32 UTC, nit23uec commented on component-models.json
> +    "id": "form",
formembed

2024-03-22 12:32 UTC, nit23uec commented on component-filters.json
> +      "form"
formembed

2024-03-22 12:33 UTC, nit23uec commented on component-definition.json
> +          "id": "form",
id should be formembed

2024-03-29 01:42 UTC, nit23uec approved these changes

2024-09-18 04:57 UTC, buuhuu commented
Closing due to inactivity. Reopen if still applicable.

2024-09-18 04:57 UTC, closed without merging